server:
  port: 8090

spring:
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10087/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
