server:
  port: 8088

spring:
  application:
    name: cart-service
  data:
    redis:
      host: 127.0.0.1:6379

eureka:
  client:
    service-url:
      default: http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

leyou:
  jwt:
    pubKeyPath: C:/tmp/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称