server:
  port: 8086

spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou

leyou:
  sms:
    accessKeyId: JWffwFJIwada
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ
    signName: 乐优商城
    verifyCodeTemplate: SMS_133976814 # 模板名称
















